// <auto-generated />
namespace ResourcePlanner.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ComplexDataModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ComplexDataModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201408291808284_ComplexDataModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
